### ISSUE TITLE
Final Project

### ISSUE THREAD

**Issue by ChandlerGotfried** [ChandlerGotfried/LGBT_Proj#3]
@AaronGullickson I made the mistake and was not clear enough. I was talking about my final project model. 
```{r textreg, results="asis", echo=FALSE}
model1 <- lm(happiness~fam_support, data=sjsd)
model2 <- lm(happiness~fam_support+out_family, data=sjsd)
model3 <- lm(happiness~fam_support*out_family+out_friends+out_neighbors+lgbt_bond+neigh_phobia+event,
             data=sjsd)
```

This is what my start to the model looks like but I am also struggling with knitting the final project too.

**Comment by AaronGullickson** [comment]
@ChandlerGotfried Those look like good models. I would put them into a screenreg/texreg for the knitting. What is the exact problem with knitting?

**Comment by ChandlerGotfried** [comment]
@AaronGullickson I try to knit the project and it doesn’t work. My graphs are fine but when I try to run my model it doesn’t show up and when I knit it gives me an error message.

**Comment by AaronGullickson** [comment]
@ChandlerGotfried Based on what I see on GH, the only problem is the compbarplot1 code chunk. You need to surround the fig.cap argument in the code chunk with quotation marks. Also don't call it Figure 1. latex will number the captions by itself.

**Comment by ChandlerGotfried** [comment]
@AaronGullickson This is the error message I get each time I try to knit my paper project

output file: main.knit.md

tlmgr search --file --global '/float.sty'

tlmgr: Remote repository is newer than local (2018 < 2019)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
! LaTeX Error: File `float.sty' not found.

! Emergency stop.
<read *> 

Error: Failed to compile main.tex. See main.log for more info.
In addition: Warning message:
In system2("tlmgr", args, ...) :
  running command ''tlmgr' search --file --global '/float.sty'' had status 1
Execution halted

**Comment by ChandlerGotfried** [comment]
@AaronGullickson I am finished with my final project. I still cannot knit it though.

**Comment by AaronGullickson** [comment]
@ChandlerGotfried 

Is the GH repo up to date? I can knit just fine. PDF is attached. 

[main.pdf](https://github.com/ChandlerGotfried/LGBT_Proj/files/3290870/main.pdf)

I believe you can fix this problem by running:

```r
tinytex::reinstall_tinytex()
```

in the R console.
